In [10]:
import numpy as np
from numpy.linalg import LinAlgError

def text_to_numbers(text):
    return [ord(char.upper()) - ord('A') + 1 for char in text if char.isalpha()]

def numbers_to_text(numbers):
    return ''.join(chr((num - 1) % 26 + ord('A')) for num in numbers)

def create_blocks(numbers, block_size):
    while len(numbers) % block_size != 0:
        numbers.append(0)
    return [numbers[i:i + block_size] for i in range(0, len(numbers), block_size)]

def is_invertible_mod_26(matrix):
    try:
        det = int(round(np.linalg.det(matrix)))
        return np.gcd(det, 26) == 1
    except LinAlgError:
        return False

def hill_cipher_encrypt(plaintext, key_matrix):
    m = key_matrix.shape[0]

    if not is_invertible_mod_26(key_matrix):
        raise ValueError("Matriks kunci TIDAK INVERTIBLE dalam mod 26")

    angka_plain = text_to_numbers(plaintext)
    blok_plain = create_blocks(angka_plain, m)

    cipher_numbers = []

    for blok in blok_plain:
        P = np.array(blok).reshape(-1, 1)
        C = np.dot(key_matrix, P) % 26
        C = C.T
        cipher_numbers.extend(C.flatten().astype(int).tolist())

    return numbers_to_text(cipher_numbers)

def input_matrix(n):
    print(f"Masukkan matriks kunci {n}x{n} (setiap baris dipisahkan spasi):")
    matrix = []
    for i in range(n):
        baris = list(map(int, input(f"Baris {i+1}: ").split()))
        if len(baris) != n:
            raise ValueError("Jumlah elemen per baris harus sama dengan ukuran matriks.")
        matrix.append(baris)
    return np.array(matrix)

if __name__ == "__main__":
    try:
        plaintext = input("Masukkan plaintext (A-Z): ").strip().upper()
        ukuran = int(input("Ukuran matriks kunci : "))
        key_matrix = input_matrix(ukuran)

        hasil_cipher = hill_cipher_encrypt(plaintext, key_matrix)

        print("\n=== HASIL ENKRIPSI HILL CIPHER ===")
        print("Plaintext  :", plaintext)
        print("Matriks Kunci:\n", key_matrix)
        print("Ciphertext :", hasil_cipher)

    except Exception as e:
        print("Terjadi kesalahan:", e)


Masukkan plaintext (A-Z):  UPUTSUKAMINUMBOBA
Ukuran matriks kunci :  3


Masukkan matriks kunci 3x3 (setiap baris dipisahkan spasi):


Baris 1:  2 7 3
Baris 2:  4 1 8
Baris 3:  5 6 9



=== HASIL ENKRIPSI HILL CIPHER ===
Plaintext  : UPUTSUKAMINUMBOBA
Matriks Kunci:
 [[2 7 3]
 [4 1 8]
 [5 6 9]]
Ciphertext : IHZBGMPSVWJFGRDKIP
